output "certificate_arn" {
  description = "The arn of certificate which generated by aws acm"
  value       = aws_acm_certificate.this.arn
}

output "domain_validation_options" {
  description = "The domain verification option for certificate debug"
  value       = aws_acm_certificate.this.domain_validation_options
}

output "certificate_status" {
  description = "The current certificate status e.g., ISSUED, PENDING_VALIDATION"
  value       = aws_acm_certificate.this.status
}